# -*- coding: utf-8 -*-
"""heartlytics_dataset_1_minor_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aO2Td0bREO4ZMGUYHa6WCCu56M-rZibE

# DATA LOADING
"""

import pandas as pd

data = pd.read_csv('data_up.csv')

data.head(5)

data.columns

data.shape

data = data.drop(columns='SEQN')

data['CoronaryHeartDisease'].value_counts()

from imblearn.over_sampling import RandomOverSampler
X = data.drop('CoronaryHeartDisease', axis=1)
y = data['CoronaryHeartDisease']
oversampler = RandomOverSampler(random_state=42)
X_resampled, y_resampled = oversampler.fit_resample(X, y)
display(y_resampled.value_counts())

df = pd.concat([X_resampled, y_resampled], axis=1)

df.isnull().sum()

"""# DATA ANALYSIS

"""

df.describe()

df.columns

df['Pulse Pressure'] = df['Diastolic'] - df['Systolic']
df['Cholestrol_ratio'] = df['Cholesterol'] / df['HDL']
df['Kidney_index'] = df['Creatinine'] / df['Uric.Acid']

df.columns

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8, 6))
sns.countplot(x='Gender', data=df)
plt.title('Distribution of Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

df = pd.get_dummies(df, columns=['Gender'])

df

correlation_matrix = df.corr()

correlation_matrix

df.shape

import numpy as np

numeric_non_boolean_cols = df.select_dtypes(include=['int64', 'float64']).columns

Q1_vals = {}
Q3_vals = {}
IQR_vals = {}

for col in numeric_non_boolean_cols:

    data_col = df[col].dropna().values
    if len(data_col) > 0:
        Q1_vals[col] = np.percentile(data_col, 25)
        Q3_vals[col] = np.percentile(data_col, 75)
        IQR_vals[col] = Q3_vals[col] - Q1_vals[col]
    else:

        Q1_vals[col] = np.nan
        Q3_vals[col] = np.nan
        IQR_vals[col] = np.nan

Q1 = pd.Series(Q1_vals)
Q3 = pd.Series(Q3_vals)
IQR = pd.Series(IQR_vals)

outliers_mask_per_col = pd.DataFrame(False, index=df.index, columns=numeric_non_boolean_cols)

for col in numeric_non_boolean_cols:
    if pd.notna(Q1[col]) and pd.notna(Q3[col]) and pd.notna(IQR[col]):
        lower_bound = Q1[col] - 1.5 * IQR[col]
        upper_bound = Q3[col] + 1.5 * IQR[col]

        outliers_mask_per_col[col] = (df[col] < lower_bound) | (df[col] > upper_bound)

final_outliers = outliers_mask_per_col.any(axis=1)

df_outliers = df[final_outliers]
df_outliers.shape

df.shape

import matplotlib.pyplot as plt
import seaborn as sns

correlation_matrix = df.corr()
correlation_with_target = correlation_matrix['CoronaryHeartDisease'].abs().sort_values(ascending=False)

plt.figure(figsize=(10, 8))
sns.barplot(x=correlation_with_target.values, y=correlation_with_target.index)
plt.title('Absolute Correlation with CoronaryHeartDisease')
plt.xlabel('Absolute Correlation Coefficient')
plt.ylabel('Features')
plt.show()

correlation_with_target

plt.figure(figsize=(8, 6))
sns.countplot(x='Diabetes', data=df)
plt.title('Distribution of Diabetes')
plt.xlabel('Diabetes')
plt.ylabel('Count')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))
sns.heatmap(correlation_matrix, cmap='coolwarm', annot=False)
plt.title('Correlation Heatmap of All Features')
plt.show()

import pandas as pd
import numpy as np

target_col = 'CoronaryHeartDisease'
corr_matrix = df.corr(numeric_only=True)
target_corr = corr_matrix[target_col].abs().sort_values(ascending=False)

upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
print(f"Original features: {df.shape[1]}")

threshold = 0.85
to_drop = set()

for column in upper.columns:
    for other_column in upper.index:
        if column != target_col and other_column != target_col:
            corr_value = upper.loc[other_column, column]
            if corr_value is not None and abs(corr_value) > threshold:
                if target_corr[column] < target_corr[other_column]:
                    to_drop.add(column)
                else:
                    to_drop.add(other_column)

print("Highly correlated features to drop (considering target relevance):")
print(sorted(to_drop))
df = df.drop(columns=list(to_drop))

print(f"Reduced features: {df.shape[1]}")

features_correlation = correlation_with_target[correlation_with_target > 0.19]
display(features_correlation)

X = df.drop(columns=['CoronaryHeartDisease'])
y = df['CoronaryHeartDisease']

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

estimator = RandomForestClassifier(random_state=42)
sf = SelectFromModel(estimator, threshold='mean', prefit=False)

X_selected_sfm = sf.fit_transform(X, y)

selected_features_mask = sf.get_support()
selected_feature_names_random_forest = X.columns[selected_features_mask]

print(f"Original number of features: {X.shape[1]}")
print(f"Number of features selected by SelectFromModel: {X_selected_sfm.shape[1]}")
print("Selected features:")
for feature in selected_feature_names_random_forest:
    print(feature)

rf = sf.estimator_
importances = rf.feature_importances_
feature_names = np.array(X.columns)

indices = np.argsort(importances)[::-1]

colors = ['green' if selected_features_mask[i] else 'gray' for i in range(len(importances))]
colors = np.array(colors)[indices]

plt.figure(figsize=(12, 6))
plt.bar(range(len(importances)), importances[indices], color=colors, edgecolor='black')
plt.xticks(range(len(importances)), feature_names[indices], rotation=90)
plt.title("RandomForest Feature Importances (Green = Selected, Gray = Dropped)", fontsize=14)
plt.xlabel("Features")
plt.ylabel("Importance Score")
plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
import matplotlib.pyplot as plt
import numpy as np

thresholds = ['mean', 'median', None]
estimator = RandomForestClassifier(random_state=42)
estimator.fit(X, y)

for t in thresholds:
    sf = SelectFromModel(estimator, threshold=t, prefit=True)
    mask = sf.get_support()
    print(f"Threshold: {t}")
    print(f"Selected features: {sum(mask)} / {X.shape[1]}")
    print(X.columns[mask].tolist())
    print()

importances = estimator.feature_importances_
indices = np.argsort(importances)[::-1]
plt.figure(figsize=(10, 6))
plt.bar(range(len(importances)), importances[indices], color='skyblue')
plt.xticks(range(len(importances)), X.columns[indices], rotation=90)
plt.title("RandomForest Feature Importances")
plt.tight_layout()
plt.show()

"""# Feature Selection

**ALGORITHM : BMPA**
"""

!ls -l

!pip install mealpy

import mealpy
import pkgutil
mods = [name for _, name, _ in pkgutil.walk_packages(mealpy.__path__, mealpy.__name__ + ".")]

print([m for m in mods if "mpa" in m.lower() or "bmpa" in m.lower()])

!pip install --upgrade git+https://github.com/thieu1995/mealpy.git scikit-learn pandas numpy -q

import pandas as pd, numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from mealpy.swarm_based.MPA import OriginalMPA
from mealpy.utils.space import BinaryVar

"""Load dataset

"""

def fitness(sol):
    mask = sol > 0.5
    if not mask.any():
        return 1
    Xs = X.loc[:, mask]

    Xtr, Xte, ytr, yte = train_test_split(Xs, y, test_size=0.2, random_state=42)
    clf = RandomForestClassifier(random_state=42).fit(Xtr, ytr)

    return 1 - accuracy_score(yte, clf.predict(Xte))

bounds = [BinaryVar() for _ in range(X.shape[1])]

"""Defining Optimization Problem



"""

problem = {
    "obj_func": fitness,
    "bounds": bounds,
    "minmax": "min",
}

"""Initializing Model and Running Binary MPA"""

model = OriginalMPA(epoch=5, pop_size=20)
result = model.solve(problem)

best_position = result.solution

if hasattr(result, "solution_fitness"):
    best_fitness = result.solution_fitness
elif hasattr(result, "fitness_history"):
    best_fitness = result.fitness_history[-1]
else:
    best_fitness = None
    print("Could not find fitness attribute in result. Inspect result.__dict__")

selected_features = np.where(best_position > 0.1)[0]
X_selected = X.iloc[:, selected_features] if selected_features.size > 0 else pd.DataFrame()

if X_selected.shape[1] > 0:
    clf_final = RandomForestClassifier(random_state=42)
    accuracy = np.mean(cross_val_score(clf_final, X_selected, y, cv=5))
else:
    accuracy = 0

print("Best Fitness (1 - Accuracy):", best_fitness)

print("Selected Features:", selected_features)

print("Total Features Selected:", len(selected_features))

print("Accuracy of Selected Features:", accuracy)

"""# MODEL SELECTION

"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB

models = {
    'RandomForestClassifier' : RandomForestClassifier(random_state=42, n_estimators=5),
    'LogisticRegression' : LogisticRegression(random_state=42),
    'SVC' : SVC(random_state=42),
    'KNeighborsClassifier' : KNeighborsClassifier(),
    'DecisionTreeClassifier' : DecisionTreeClassifier(
    criterion='gini',
    max_depth=5,
    min_samples_leaf=1,
    min_samples_split=2,
    random_state=42
),
    'GaussianNB' : GaussianNB(),
    'LGBMClassifier' : LGBMClassifier(random_state=42),
    'XGBClassifier' : XGBClassifier(random_state=42),
    'BaggingClassifier' : BaggingClassifier(random_state=42),
}

X = df.drop(columns=['CoronaryHeartDisease'])
y = df['CoronaryHeartDisease']

filtered_X = X[selected_feature_names_random_forest.tolist()]
display(filtered_X.head())

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, roc_auc_score
from sklearn.preprocessing import StandardScaler
ml_model_results = []
scaler = StandardScaler()
filtered_X = scaler.fit_transform(filtered_X)
for name, model in models.items():
    X_train, X_test, y_train, y_test = train_test_split(filtered_X, y, test_size=0.2, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_pred)
    train_accuracy = accuracy_score(y_train, model.predict(X_train))
    recall = recall_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    ml_model_results.append([name, test_accuracy, train_accuracy, recall, precision, f1, roc_auc])

ml_model_results_df = pd.DataFrame(ml_model_results, columns=['Model', 'Test Accuracy', 'Train Accuracy', 'Recall', 'Precision', 'F1 Score', 'ROC-AUC'])

ml_model_results_df

# random forest classifer
random_forest_metrics = []
n_estimator = [3, 5, 10]
for n in n_estimator:
  model = RandomForestClassifier(random_state=42, n_estimators=n)
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  test_accuracy = accuracy_score(y_test, y_pred)
  train_accuracy = accuracy_score(y_train, model.predict(X_train))
  recall = recall_score(y_test, y_pred)
  precision = precision_score(y_test, y_pred)
  f1 = f1_score(y_test, y_pred)
  random_forest_metrics.append([n, test_accuracy, train_accuracy, recall, precision, f1])

random_forest_metrics_df = pd.DataFrame(random_forest_metrics, columns=['n_estimators', 'Test Accuracy', 'Train Accuracy', 'Recall', 'Precision', 'F1 Score'])
random_forest_metrics_df

from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

X_train, X_test, y_train, y_test = train_test_split(filtered_X, y, test_size=0.2, random_state=42)
xgb = XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    use_label_encoder=False,
    random_state=42
)
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.05, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}
grid_search = GridSearchCV(
    estimator=xgb,
    param_grid=param_grid,
    scoring='accuracy',
    cv=3,
    verbose=1,
    n_jobs=-1
)
grid_search.fit(X_train, y_train)
best_xgb = grid_search.best_estimator_
print("Best Parameters:", grid_search.best_params_)
y_pred = best_xgb.predict(X_test)

xgbm_metrics = {
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1 Score": f1_score(y_test, y_pred),
    "ROC-AUC": roc_auc_score(y_test, y_pred)
}

print("XGBM Metrics:")
for k, v in xgbm_metrics.items():
    print(f"{k}: {v:.4f}")

from sklearn.metrics import classification_report
xgbm_model_with_tuned_params = XGBClassifier(
    colsample_bytree=0.8,
    eval_metric='logloss',
    learning_rate=0.1,
    max_depth=7,
    n_estimators=200,
    objective='binary:logistic',
    subsample=0.8,
    use_label_encoder=False,
    random_state=42
)
xgbm_model_with_tuned_params.fit(X_train, y_train)
y_pred = xgbm_model_with_tuned_params.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)
classification_Report_xgbm = classification_report(y_test, y_pred)
print("Test Accuracy:", test_accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC-AUC:", roc_auc)
print("Classification Report:\n", classification_Report_xgbm)

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

y_pred_proba = xgbm_model_with_tuned_params.predict_proba(X_test)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6, 6))
plt.plot(fpr, tpr, color='blue', lw=2, label=f'ROC curve (AUC = {roc_auc:.3f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - XGBoost Model')
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

# decision tree classifier algorithm
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 10, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
}

grid_search = GridSearchCV(estimator=dt, param_grid=param_grid,
                           cv=5, scoring='accuracy', n_jobs=-1, verbose=1)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow import keras

scaler = StandardScaler()
X_selected_scaled = scaler.fit_transform(filtered_X)
X_train, X_test, y_train, y_test = train_test_split(filtered_X, y, test_size=0.2, random_state=42)
model_mlp = keras.Sequential([
    keras.layers.Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.3),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dropout(0.3),

    keras.layers.Dense(64, activation='relu'),
    keras.layers.BatchNormalization(),

    keras.layers.Dense(1, activation='sigmoid')
])
opt = keras.optimizers.Adam(learning_rate=0.0005)
model_mlp.compile(optimizer=opt,
                  loss='binary_crossentropy',
                  metrics=['accuracy'])
early_stop = keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)
history = model_mlp.fit(
    X_train, y_train,
    epochs=200,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stop],
    verbose=1
)

test_loss, test_acc = model_mlp.evaluate(X_test, y_test)
print(f"\nTest Accuracy: {test_acc:.4f}")

print(selected_feature_names_random_forest.tolist())

input_data_from_user = {
    'Age': 55,
    'Systolic': 130,
    'Lymphocyte': 2.5,
    'Platelet-count': 250,
    'Cholesterol': 190,
    'Creatinine': 1.0,
    'Glucose': 95,
    'Glycohemoglobin': 5.8,
    'Diastolic': 45
}

modified_data = {
    'Age': input_data_from_user['Age'],
    'Systolic': input_data_from_user['Systolic'],
    'Lymphocyte': input_data_from_user['Lymphocyte'],
    'Platelet-count': input_data_from_user['Platelet-count'],
    'Cholesterol': input_data_from_user['Cholesterol'],
    'Creatinine': input_data_from_user['Creatinine'],
    'Glucose': input_data_from_user['Glucose'],
    'Glycohemoglobin': input_data_from_user['Glycohemoglobin'],
    'Pulse Pressure': input_data_from_user['Systolic'] - input_data_from_user['Diastolic']
}

print(modified_data)

input_df_for_prediction = pd.DataFrame([modified_data])
input_df_for_prediction

prediction = xgbm_model_with_tuned_params.predict(input_df_for_prediction)[0]
print("Heart Disease Risk (0=No, 1=Yes):", prediction)

import joblib
joblib.dump(xgbm_model_with_tuned_params, 'xgbm_model_with_tuned_params.pkl')